# ground_truth
#
# This is a function to prepare ground truth data set for pseudouridylation identification
# which run ground_truth and return ground truth rRNA data for running ROC/SVM/ANN or other machine learning/deep learning method.

#' Prepare ground truth data set for pseudouridylation identification
#' @param RpsiScan_res_file The psiScan result file generated by RpsiScan function
#' @param known_rRNA_bed The path to the known rRNA pseudouridylation bed file
#' @param rrna_chr21_bed The path to the gene region of rRNA bed file
#' @param output_dir The path to the output directory
#' @param output_name The name to the output file
#' @export
#'
ground_truth <- function(RpsiScan_res_file,
                       known_rRNA_bed,
                       rrna_chr21_bed,
                       output_dir,
                       output_name
                      )
{
  # cmd1: bedtools intersect -a ${outFileName}_roc_filt.bed -b $(dirname "$0")/hg38_human_chr21_rRNA_known_pseudoU_SingleSites.bed -s > ${outFileName}_knowpse.bed
  # cmd2: bedtools intersect -a ${outFileName}_roc_filt.bed -b $(dirname "$0")/rrna_chr21.bed -s > ${outFileName}_rrna.bed
  # cmd3: bedtools intersect -a ${outFileName}_rrna.bed -b $(dirname "$0")/hg38_human_chr21_rRNA_known_pseudoU_SingleSites.bed -s -v > ${outFileName}_notpse.bed
  # cmd4: cat ${outFileName}_knowpse.bed |awk 'FS=OFS="\t" {print $0,"1"}' > ${outFileName}_knowpse.txt
  # cmd5: cat ${outFileName}_notpse.bed |awk 'FS=OFS="\t" {print $0,"0"}' > ${outFileName}_notpse.txt
  # cmd6: cat ${outFileName}_knowpse.txt ${outFileName}_notpse.txt > ${outFileName}_roc_plot.txt

  if (!dir.exists(output_dir)) {
    dir.create(output_dir)
  }

  bedtools_path <- system.file("program", "bedtools", package = "RpsiScan")

  if (bedtools_path!="") {
    print("bedtools exist!")
    system(paste("chmod 777", bedtools_path, sep=" "))
  }else{
    print("bedtools.static not exist! Downloading...")
    url<-"https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static"
    download.file(url, destfile = paste(system.file("program", package = "RpsiScan"),"bedtools",sep="/"))
    bedtools_path <- system.file("program", "bedtools", package = "RpsiScan")
    system(paste("chmod 777", bedtools_path, sep=" "))
  }

  output_dir_output_name<-paste(output_dir,"/",output_name,sep="")
  knowpse_bed<-paste(output_dir_output_name,"_knowpse.bed",sep="")
  rrna_bed<-paste(output_dir_output_name,"_rrna.bed",sep="")
  notpse_bed<-paste(output_dir_output_name,"_notpse.bed",sep="")

  knowpse_txt<-paste(output_dir_output_name,"_knowpse.txt",sep="")
  notpse_txt<-paste(output_dir_output_name,"_notpse.txt",sep="")
  roc_plot_txt<-paste(output_dir_output_name,"_roc_plot.txt",sep="")

  print(bedtools_path)
  cmd1 <- paste(bedtools_path,
                "intersect",
                "-a", RpsiScan_res_file,
                "-b", known_rRNA_bed,
                "-s",
                ">",
                knowpse_bed,
                sep=" ")
  print(cmd1)
  system(cmd1)
  assign(paste(output_name,"_knowpse_bed_R",sep=""),fread(knowpse_bed),envir = .GlobalEnv)

  cmd2 <- paste(bedtools_path,
                "intersect",
                "-a", RpsiScan_res_file,
                "-b", rrna_chr21_bed,
                "-s",
                ">",
                rrna_bed,
                sep=" ")
  print(cmd2)
  system(cmd2)
  assign(paste(output_name,"_rrna_bed_R",sep=""),fread(rrna_bed),envir = .GlobalEnv)

  cmd3 <- paste(bedtools_path,
                "intersect",
                "-a", rrna_bed,
                "-b", known_rRNA_bed,
                "-s",
                "-v",
                ">",
                notpse_bed,
                sep=" ")
  print(cmd3)
  system(cmd3)
  assign(paste(output_name,"_notpse_bed_R",sep=""),fread(notpse_bed),envir = .GlobalEnv)

  cmd4 <- paste("cat",
                knowpse_bed,
                "|awk 'FS=OFS=\"\t\" {print $0,\"1\"}' >",
                knowpse_txt,
                sep=" ")
  print(cmd4)
  system(cmd4)
  assign(paste(output_name,"_knowpse_txt_R",sep=""),fread(knowpse_txt),envir = .GlobalEnv)

  cmd5 <- paste("cat",
                notpse_bed,
                "|awk 'FS=OFS=\"\t\" {print $0,\"0\"}' >",
                notpse_txt,
                sep=" ")
  print(cmd5)
  system(cmd5)
  assign(paste(output_name,"_notpse_txt_R",sep=""),fread(notpse_txt),envir = .GlobalEnv)

  cmd6 <- paste("cat",
                knowpse_txt,
                notpse_txt,
                ">",
                roc_plot_txt,
                sep=" ")
  print(cmd6)
  system(cmd6)
  assign(paste(output_name,"roc_plot_txt_R",sep=""),fread(roc_plot_txt),envir = .GlobalEnv)

  print(paste("ground_truth result in",output_dir,sep=" "))
}
