# mod_info
#
# This is a function to prepare modification information data set for snoRNA-target interaction scanning

#' Prepare modification information data set for snoRNA-target interaction scanning
#' @param RpsiScan_res_file The psiScan result file generated by RpsiScan function
#' @param RpsiAnnotator_res_file The psiAnnotator result file generated by RpsiAnnotator function
#' @param psiU.SingleSites.bed pseudouridylation sites in bed format, default we recommend hg38.psiU.SingleSites.bed
#' @param pred_method prediction method, current version provided option: 'roc', 'user-defined','svm','ann'
#' @param output_dir The path to the output directory
#' @param output_name The name to the output file
#' @export
#'
mod_info <- function(RpsiScan_res_file,
                     RpsiAnnotator_res_file,
                     psiU.SingleSites.bed,
                     pred_method,
                     output_dir,
                     output_name)
{
  # cmd1: cat $annobedfile | cut -f 1-6 > ${annobedfile}6
  # cmd2: cat $annobedfile |awk 'FS=OFS="\t" {print ""$1"_"$2"_"$3"_"$6"",$5,$7}' > ${annobedfile}6.append
  # cmd3: bedtools intersect -a $bedfile -b ${annobedfile}6 -s > ${bedfile%.bed}_anno_info.bed
  # cmd4: bedtools intersect -a ${bedfile%.bed}_anno_info.bed -b $(dirname "$0")/hg38.psiU.SingleSites.bed -wb|awk 'FS=OFS="\t" {print ""$1"_"$2"_"$3"_"$6"",$43,$39}' > ${bedfile%.bed}.known.target
  # cmd5: bedtools intersect -a ${bedfile%.bed}_anno_info.bed -b $(dirname "$0")/hg38.psiU.SingleSites.bed -wb -v |awk 'FS=OFS="\t" {print ""$1"_"$2"_"$3"_"$6"","unknown",$39}' > ${bedfile%.bed}.unknown.target
  # cmd6: cat ${bedfile%.bed}.known.target ${bedfile%.bed}.unknown.target > ${bedfile%.bed}_modinfo.txt
  # cmd7: sed -i -e 's/T/U/g' ${bedfile%.bed}_modinfo.txt

  if (!dir.exists(output_dir)) {
    dir.create(output_dir)
  }

  bedtools_path <- system.file("program", "bedtools", package = "RpsiScan")

  if (bedtools_path!="") {
    print("bedtools exist!")
    system(paste("chmod 777", bedtools_path, sep=" "))
  }else{
    print("bedtools.static not exist! Downloading...")
    url<-"https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static"
    download.file(url, destfile = paste(system.file("program", package = "RpsiScan"),"bedtools",sep="/"))
  }

  output_dir_output_name<-paste(output_dir,"/",output_name,sep="")

  RpsiAnnotator_res_file6<-paste(output_dir,"/",basename(sub(".bed",".bed6",RpsiAnnotator_res_file)),sep="")
  RpsiAnnotator_res_file6.append<-paste(output_dir,"/",basename(sub(".bed",".bed6.append",RpsiAnnotator_res_file)),sep="")
  anno_info.bed<-paste(output_dir,"/",basename(sub(".bed","_anno_info.bed",RpsiAnnotator_res_file)),sep="")
  known.target<-paste(output_dir,"/",basename(sub(".bed",".known.target",RpsiAnnotator_res_file)),sep="")
  unknown.target<-paste(output_dir,"/",basename(sub(".bed",".unknown.target",RpsiAnnotator_res_file)),sep="")
  modinfo<-paste(output_dir,"/",basename(sub(".bed","_modinfo.txt",RpsiScan_res_file)),sep="")


  cmd1 <- paste("cat",
                RpsiAnnotator_res_file,
                "|cut -f 1-6 >",
                RpsiAnnotator_res_file6,
                sep=" ")
  print(cmd1)
  system(cmd1)
  assign(paste(output_name,"_RpsiAnnotator_res_file6_R",sep=""),fread(RpsiAnnotator_res_file6,fill=TRUE),envir = .GlobalEnv)

  cmd2 <- paste("cat",
                RpsiAnnotator_res_file,
                "|awk \'FS=OFS=\"\t\" {print \"\"$1\"_\"$2\"_\"$3\"_\"$6\"\",$5,$7}\' >",
                RpsiAnnotator_res_file6.append,
                sep=" ")
  print(cmd2)
  system(cmd2)
  assign(paste(output_name,"_RpsiAnnotator_res_file6.append_R",sep=""),fread(RpsiAnnotator_res_file6.append,fill=TRUE),envir = .GlobalEnv)

  cmd3 <- paste(bedtools_path,
                "intersect",
                "-a", RpsiScan_res_file,
                "-b", RpsiAnnotator_res_file6,
                "-s",
                ">",
                anno_info.bed,
                sep=" ")
  print(cmd3)
  system(cmd3)
  assign(paste(output_name,"_anno_info.bed_R",sep=""),fread(anno_info.bed),envir = .GlobalEnv)

  if(pred_method=="roc"){
    cmd4 <- paste(bedtools_path,
                  "intersect",
                  "-a", anno_info.bed,
                  "-b", psiU.SingleSites.bed,
                  "-wb|awk \'FS=OFS=\"\t\" {print \"\"$1\"_\"$2\"_\"$3\"_\"$6\"\",$47,$42}\' >",#roc prediction result
                  known.target,
                  sep=" ")
  }else if(pred_method=="user-defined"){
    cmd4 <- paste(bedtools_path,
                  "intersect",
                  "-a", anno_info.bed,
                  "-b", psiU.SingleSites.bed,
                  "-wb|awk \'FS=OFS=\"\t\" {print \"\"$1\"_\"$2\"_\"$3\"_\"$6\"\",$44,$39}\' >",#user-defined prediction result
                  known.target,
                  sep=" ")
  }else if(pred_method=="svm"){
    cmd4 <- paste(bedtools_path,
                  "intersect",
                  "-a", anno_info.bed,
                  "-b", psiU.SingleSites.bed,
                  "-wb|awk \'FS=OFS=\"\t\" {print \"\"$1\"_\"$2\"_\"$3\"_\"$6\"\",$52,$42}\' >",#svm prediction result
                  known.target,
                  sep=" ")
  }else if(pred_method=="ann"){
    cmd4 <- paste(bedtools_path,
                  "intersect",
                  "-a", anno_info.bed,
                  "-b", psiU.SingleSites.bed,
                  "-wb|awk \'FS=OFS=\"\t\" {print \"\"$1\"_\"$2\"_\"$3\"_\"$6\"\",$49,$42}\' >",#ann prediction result
                  known.target,
                  sep=" ")
  }else{
    print(paste("Error file input: ",RpsiScan_res_file,sep=""))
  }

  print(cmd4)
  system(cmd4)
  assign(paste(output_name,"_known.target_R",sep=""),fread(known.target),envir = .GlobalEnv)

  if(pred_method=="roc"){
    cmd5 <- paste(bedtools_path,
                  "intersect",
                  "-a", anno_info.bed,
                  "-b", psiU.SingleSites.bed,
                  "-wb|awk \'FS=OFS=\"\t\" {print \"\"$1\"_\"$2\"_\"$3\"_\"$6\"\",\"unknown\",$42}\' >",#roc prediction result
                  unknown.target,
                  sep=" ")
  }else if(pred_method=="user-defined"){
    cmd5 <- paste(bedtools_path,
                  "intersect",
                  "-a", anno_info.bed,
                  "-b", psiU.SingleSites.bed,
                  "-wb|awk \'FS=OFS=\"\t\" {print \"\"$1\"_\"$2\"_\"$3\"_\"$6\"\",\"unknown\",$39}\' >",#user-defined prediction result
                  unknown.target,
                  sep=" ")
  }else if(pred_method=="svm"){
    cmd5 <- paste(bedtools_path,
                  "intersect",
                  "-a", anno_info.bed,
                  "-b", psiU.SingleSites.bed,
                  "-wb|awk \'FS=OFS=\"\t\" {print \"\"$1\"_\"$2\"_\"$3\"_\"$6\"\",\"unknown\",$42}\' >",#svm prediction result
                  unknown.target,
                  sep=" ")
  }else if(pred_method=="ann"){
    cmd5 <- paste(bedtools_path,
                  "intersect",
                  "-a", anno_info.bed,
                  "-b", psiU.SingleSites.bed,
                  "-wb|awk \'FS=OFS=\"\t\" {print \"\"$1\"_\"$2\"_\"$3\"_\"$6\"\",\"unknown\",$42}\' >",#ann prediction result
                  unknown.target,
                  sep=" ")
  }else{
    print(paste("Error file input: ",RpsiScan_res_file,sep=""))
  }

  print(cmd5)
  system(cmd5)
  assign(paste(output_name,"_unknown.target_R",sep=""),fread(unknown.target),envir = .GlobalEnv)

  cmd6 <- paste("cat",
                known.target,
                unknown.target,
                ">",
                modinfo,
                sep=" ")
  print(cmd6)
  system(cmd6)
  assign(paste(output_name,"_modinfo_txt_R",sep=""),fread(modinfo),envir = .GlobalEnv)

  cmd7 <- paste("sed",
                "-i -e \'s/T/U/g\'",
                modinfo,
                sep=" ")
  print(cmd7)
  system(cmd7)
  assign(paste(output_name,"_modinfo_R",sep=""),fread(modinfo),envir = .GlobalEnv)

  print(paste("mod_info result in",output_dir,sep=" "))
}
