# udfilt
#
# Filt out undesired psiScan information by six key identification thresholds

#' Filt out undesired psiScan information by six key identification thresholds
#' @param RpsiScan_res_file The psiScan result file generated by RpsiScan function
#' @param tretRtsRatio_thres The filtering threshold for tretRtsRatio
#' @param rtsRatioFold_thres The filtering threshold for rtsRatioFold
#' @param tretBefRatio_thres The filtering threshold for tretBefRatio
#' @param befRatioFold_thres The filtering threshold for befRatioFold
#' @param aftRatioFold_thres The filtering threshold for aftRatioFold
#' @param tretMutRatio_thres The filtering threshold for tretMutRatio
#' @param mutRatioFold_thres The filtering threshold for mutRatioFold
#' @param tretDelRatio_thres The filtering threshold for tretDelRatio
#' @param delRatioFold_thres The filtering threshold for delRatioFold
#' @param output_dir The path to the output directory
#' @param output_name The path to the output file
#' @export
#'
udfilt <- function(RpsiScan_res_file,
                   tretRtsRatio_thres,
                   rtsRatioFold_thres,
                   tretBefRatio_thres,
                   befRatioFold_thres,
                   tretAftRatio_thres,
                   aftRatioFold_thres,
                   tretMutRatio_thres,
                   mutRatioFold_thres,
                   tretDelRatio_thres,
                   delRatioFold_thres,
                   output_dir,
                   output_name)
{
  RpsiScan_res_file<-fread(RpsiScan_res_file)
  udfilt_res<-RpsiScan_res_file %>% mutate(class = if_else(tretRtsRatio>tretRtsRatio_thres &
                                                             rtsRatioFold>rtsRatioFold_thres &
                                                             tretBefRatio>tretBefRatio_thres &
                                                             befRatioFold>befRatioFold_thres &
                                                             tretAftRatio>tretAftRatio_thres &
                                                             aftRatioFold>aftRatioFold_thres &
                                                             tretMutRatio>tretMutRatio_thres &
                                                             mutRatioFold>mutRatioFold_thres &
                                                             tretDelRatio>tretDelRatio_thres &
                                                             delRatioFold>delRatioFold_thres, 1, 0))
  output_dir_output_name<-paste(output_dir,"/",output_name,sep="")
  fwrite(x=udfilt_res,file=paste(output_dir_output_name,".txt",sep=""),sep="\t")
  write.table(udfilt_res,paste(output_dir_output_name,".bed",sep=""),row.names=F,col.names=F,quote=F,sep="\t")
  return(udfilt_res)
}
